### ISSUE TITLE
Can't Download Libraries

### ISSUE THREAD

**Issue by BladeKing1** [ubis/Freya#2]

**Comment by BladeKing1** [comment]
I receive this error, "go get: malformed module path "loginserver": missing dot in first path element", after typing the "go get -v loginserver" command as the installation page says. I have Go installed, and my GOPATH is correct.

**Comment by BladeKing1** [comment]
Any help would be greatly appreciated.

**Comment by 7cherubin** [comment]
Use Go version  go1.10

**Comment by DJ-Rei** [comment]
I received the same error initially and when I took a look at the source code and wiki, it (Freya) uses extremely outdated functions and deprecated features of GoLang. I am currently in the process of fixing all of these (even though this isn't my project, I will still contribute to it). Also, the last time this project got updated looks like it was over a year ago from the time of my posted reply. I will try to get this to work. Ultimately, the key word is ***TRY***

**Comment by ubis** [comment]
Hi,

I could migrate Freya to go modules. I'm still quite surprised that Freya received any attention, it's been years since I've worked on it.

**Comment by ubis** [comment]
It should be buildable in [go_modules](https://github.com/ubis/Freya/tree/go_modules) branch:

![Screenshot 2023-07-25 at 08 39 14](https://github.com/ubis/Freya/assets/3310376/24e1c41e-0ed9-4070-bdbf-c9e432437fe3)

Although I think overall project structure can be improved further, I will not merge `go_modules` branch into `development`, yet.

@DJ-Rei Do you have EP8 client? Could you check if it's working?

**Comment by ubis** [comment]
I've checked with EU & NA EP8 clients, both are working.

This is fixed since 33f5a3844c308bc0cb72bccff61fcb8af99b436e.

**Comment by DJ-Rei** [comment]
Thanks. It has been years since I wound up working with GoLang so I have seen no issues with the code you made. I obviously didn't know about half of the features that got added and/or deprecated. I was spending way more time than I wanted to trying to figure this out, but I still stuck with it because I wished to contribute to something new.

**Comment by ubis** [comment]
You can peek into [entering_world_new](https://github.com/ubis/Freya/tree/feature/entering_world_new) branch, recently I've added ability to enter the world, show online players, chat (normal & trade) as well as player movement.

**Comment by DJ-Rei** [comment]
Do you maybe want to continue this talk off this issue topic? Just so we don't clutter an issues even more.
I have an IRC channel if you wanted to use that or I can use discord if needed. [@reij2125 is my discord tag] [#freya under irc.libera.chat IRC server]
